### ISSUE TITLE
[Debian bug 843053] ABI breakage

### ISSUE THREAD

**Issue by proycon** [LanguageMachines/libfolia#10]
Frog (and ucto?) break in debian because of a symbol error: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=843053

The packages were compiled with libfolia 1.4, but state dependency requirement (>= 1.3). I assume the user still has libfolia v1.3 then and the ABI changed in the meantime? It sounds like we need to increase the so version for every ABI change to prevent such issues? Or tighten the package dependencies even more strictly if that suffices.

**Comment by kosloot** [comment]
ok, have Frog en Ucto depending on Libfolia 1.4 is a good plan anyway.
I suggest to have the soname bumped in the upcoming 1.5 release of Libfolia.
it is a bug-fix release, but maybe good to release soon?

**Comment by proycon** [comment]
The user did use 1.4 after all it seems, I managed to reproduce this on a fresh debian. I'm wondering what caused this, maybe I accidentally packaged Frog against an older libfolia... I'll try to create a new package.

```
$ frog
frog: symbol lookup error: /usr/lib/libfrog.so.1: undefined symbol: _ZNK5folia24AbstractStructureElement3strERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE
```

**Comment by proycon** [comment]
Update plan:

* We bump the soname version in libfolia upstream to 5.0.0 (was: 4.0.0)     
* We release upstream and update the debian package                                                                                                                          
* bump the libfolia4 package to libfolia5 (and adapt libfolia5.install accordingly) and make libfolia-dev depend on libfolia5 instead of libfolia4                                                  
* Considering the only packages relying on libfolia, both in debian but also in general, are our own (ucto & frog), just release the new libfolia package along with a new ucto and frog package that depend on it and forego on any transitions

**Comment by proycon** [comment]
Latest libfolia release should solve this. Package built and submitted, pending review and upload by debian sponsor now.
