### ISSUE TITLE
Update debian package for v1.15

### ISSUE THREAD

**Issue by proycon** [LanguageMachines/libfolia#15]
Note: SO version bump!

**Comment by proycon** [comment]
@kosloot: Question on SO versions and debian packaging. We currently we have a ``libfolia6`` package in debian, from libfolia v1.6, initially that produced ``libfolia.so.6.0.0``, but the latest release bumps this to ``libfolia.so.6.0.3``. The version bump looks a bit too minor to me because we have ABI breakage again (I tested this in this case, old 0.9.6 ucto package doesn't work with newest libfolia binary; symbols not found).

I have to name the libfolia package differently if ABI breaks. We had ``libfolia5`` and ``libfolia4`` prior to this, so ``libfolia7`` would make most sense I guess, otherwise we have to invent yet another version naming scheme like libfolia-6.0.3 which seems rather messy and inconsistent with past practice, I could also do libfolia10 (in reference to the v1.10), but then the so version (6.0.3) bears no relation to that. What do you think?

We also need to make very sure there are no ABI breakages in ticcutils and ucto, otherwise I have to change those package names too (see LanguageMachines/ticcutils#8 and LanguageMachines/ucto#36)

**Comment by kosloot** [comment]
v1.101.1 is released with .so version 7.0.0
libfolia7 looks fine with me.

**Comment by proycon** [comment]
Ready on alioth

**Comment by proycon** [comment]
ready on Alioth again

**Comment by proycon** [comment]
Process feedback from sponsor

**Comment by kosloot** [comment]
1.13 is released already...

**Comment by proycon** [comment]
yeah, the debian releases are on the back burner lately in favour of LaMachine work

**Comment by proycon** [comment]
Ready on [salsa](https://salsa.debian.org/science-team/libfolia). Addresses https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=915624
