### ISSUE TITLE
Implement support for provenance data

### ISSUE THREAD

**Issue by proycon** [LanguageMachines/libfolia#28]
FoLiA v2.0 documents may now carry provenance data, an annotationtype uses either this or the old system of annotators

* [ ] - Implement parsing of provenance data (holding ``<processor>`` elements)
* [ ] - Implement parsing of ``<annotator>`` elements in the annotation declarations, this is what links declarations to processors in the provenance data
* [ ] - Implement parsing of ``processor`` attribute (a common FoLiA attribute that links any element to its processor, analogous to annotator/annotatortype pre-2.0)
* [ ] - Implement serialisation of provenance data
* [ ] - Implement serialisation of ``<annotator>``
* [ ] - Implement serialisation of the ``processor`` attribute
* [ ] - Implement an API for setting the processor (see proycon/foliapy#9)

See:
* original issue: proycon/folia#46
* documentation: https://folia.readthedocs.io/en/latest/metadata.html#provenance-data

**Comment by kosloot** [comment]
In libfolia now
