### ISSUE TITLE
Implement stricter declarations but retain backward compatibility.

### ISSUE THREAD

**Issue by proycon** [LanguageMachines/libfolia#29]
FoLiA v2.0 requires everything that has an annotationtype to be declared, which makes things simpler. However, since we need to retain backward compatibility we also need to keep supporting the pre-v2 situation.. See the closing post in https://github.com/proycon/folia/issues/54 for a summary.

The Python library actually does a of declarations implicitly (I have a ``Document.autodeclare`` that now defaults to True, but I don't think the C++ version necessarily requires such extra convenience function)

**Comment by kosloot** [comment]
In libfolia now
