### ISSUE TITLE
Implement group annotations

### ISSUE THREAD

**Issue by proycon** [LanguageMachines/libfolia#33]
Group annotations provide the ability to add inline annotations on multi-word spans (group annotations) and solved related multi-word issues. These were previously reserved only for use with structural elements. See proycon/folia#51

AbstractInlineAnnotation is now in AbstractSpanAnnotation.ACCEPTED_DATA to allow this, but the library has to check if the declaration actually allows it.

**Comment by kosloot** [comment]
FoLiA 2.0 is released
