### ISSUE TITLE
String Element should support str()

### ISSUE THREAD

**Issue by kosloot** [LanguageMachines/libfolia#4]
using str() on s String element yield the default word 'str' (the tagname)
text() is working correctly, so a workaround is available.
But str() should work too.

Maybe it is better to define str() in terms of text() generally?

**Comment by proycon** [comment]
``str()`` should just be aliased to ``text()`` in most cases yes (but ``phon()`` for PhonContent!), it's there in the Python version as ``__str__()``, the default pythonic mathod to overload to serialise to string. Keeping a ``str()`` method in the C++ version makes less sense I guess. Perhaps consider an ``operator<<`` overload for an ostream instead.

**Comment by kosloot** [comment]
OK. But str() is there, so it is not a good idea to remove it (backward compatibility)
But atm it is only defined for AbstractStructureElement, which String isn't.
PhonContent() is a good point. !
str() should remain virtual, but overloaded for way more classes then AbstractStructure only.

**Comment by kosloot** [comment]
libfolia now delivers text() for all nodes that have TextContent.
This includes String.
for PhonContent support is lagging behind

**Comment by kosloot** [comment]
so str() returns text() is applicable, and phon() otherwise.
But what if BOTH are available?
e.g. Utterance may contain both TextContent AND PhonContent.

**Comment by kosloot** [comment]
The currennt implementation prefers TextContent over PhonContent
I consider this issue closed
