### ISSUE TITLE
Forward-compatibility: less strict version checking

### ISSUE THREAD

**Issue by proycon** [LanguageMachines/libfolia#6]
Right now libfolia refuses to read newer FoLiA files than known at the time of compilation:

    $ folialint example.xml
    FAIL: XML error: XML error: FoLiA Document has unsupported version: 1.3 (1.2.0 is supported.)

I propose we become a bit less strict and do not immediately refuse to parse newer FoLiA documents. Instead we should output a very clear warning that the document is newer and that any failures that occur after that point are most likely related to that fact. In practice newer FoLiA documents do not necessarily use features that were not present in earlier versions, so in many cases parsing would work, although it is of course no longer guaranteed, the bigger the version discrepancy the larger the chance of failure.

I think such behaviour may be preferable in cases where people linger on older versions of libfolia for a bit longer (as in debian for instance). I already got one support question related to this a while back.

**Comment by kosloot** [comment]
Done.
